server:
  port: ${PORT:8080}
  #port:8080 # Set port for you Spring Boot Application

spring:
  profiles:
    active: db
  datasource:
    url: jdbc:postgresql://ep-raspy-mouse-a1r0te7a.ap-southeast-1.aws.neon.tech/expensedb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: expensedb_owner
    password: npg_bVI1Ldstv0YK
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect